### ISSUE TITLE
[BUG] Command prompt version IDs have changed

### ISSUE THREAD

**Issue by jakowenko** [erictik/midjourney-client#124]
### the code that reproduces this issue or a replay of the bug

All examples are currently failing.

### Describe the bug

It appears that the version ID of the prompts has changed. I'm guessing related to this message Midjourney posted.

![image](https://github.com/erictik/midjourney-api/assets/1081811/958395be-6bfc-433c-a420-f2d1e271c267)

I was able to verify the version changed for at least info and imagine. It might be a good idea to make these as config options so the user can change them w/o requiring a package rebuild.

### error log

Error 400 from ImagineApi

**Comment by iamkunal9** [comment]
Opened the pull req with the fix!
@jakowenko

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-api/commit/a15e8c70c78d7116af28092c49ad6bec99f000fd#diff-eb2670564ae072c1d316a239d83b7e1ff892808d117e9e232d9d98db4be6fdd4

**Comment by stricklandye** [comment]
@iamkunal9 I have also encoutered this sistuation. Do you know how to fix this permanently instead of updating version manaully every time.

**Comment by stricklandye** [comment]
@ondraasek FIrst, opening browser's dev too. then back to discord, typing `/imagine <your prompt>` then find http request named `interaction` in dev tool,click payload tab you will find the `version: 1118961510123847772 `  in json body

**Comment by treefort** [comment]
Thanks for fixing this so fast!

If we expect these version numbers to change moving forward, it probably makes sense to be able to override them with environment variables so projects stay running between code updates. 💯

**Comment by iamkunal9** [comment]
> @iamkunal9 I have also encoutered this sistuation. Do you know how to fix this permanently instead of updating version manaully every time.

For now we have to do it manually it depends on the midjourney updates.

**Comment by stricklandye** [comment]
> > @iamkunal9 I have also encoutered this sistuation. Do you know how to fix this permanently instead of updating version manaully every time.
> 
> For now we have to do it manually it depends on the midjourney updates.

I see. Thanks.
