### ISSUE TITLE
What is flags mean in the Upscale API？

### ISSUE THREAD

**Issue by rictt** [erictik/midjourney-client#138]
### the code that reproduces this issue or a replay of the bug

client.Upscale({
        content: prompt,
        index: index as 1 | 2 | 3 | 4,
        msgId,
        hash: msgHash,
        loading: (uri: string) => {
        },
      })

### Describe the bug

**Describe the bug**
i'm using version was @3.0.8,when i trying to upscale image by use Upscale API, the console.log tell me parameter can't not match the API params! I lookup the source, but i have not idea what flags the api need

**Expected behavior**

**Screenshots**

### error log

Property 'flags' is missing in type '{ content: string; index: 1 | 2 | 3 | 4; msgId: string; hash: string; loading: (uri: string) => void; }' but required in type '{ index: 1 | 2 | 3 | 4; msgId: string; hash: string; content?: string; flags: number; loading?: LoadingHandler; }'.

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-client/blob/main/example/upscale-ws.ts

**Comment by rictt** [comment]
Thanks, I just found that the document has an example of the opposite of the update
