### ISSUE TITLE
在discord中成功画了内容，但是没有返回

### ISSUE THREAD

**Issue by xiaoqixiaoqi1113** [erictik/midjourney-client#142]
### the code that reproduces this issue or a replay of the bug

![image](https://github.com/erictik/midjourney-client/assets/107258825/c3bcf758-d825-4e67-b491-7249bc8dfb09)
![image](https://github.com/erictik/midjourney-client/assets/107258825/5a9c1351-88bb-4ca3-b281-572758a05999)

这是我的配置项

const client = new Midjourney({
    ServerId: process.env.SERVER_ID,
    ChannelId: process.env.CHANNEL_ID,
    SalaiToken: process.env.SALAI_TOKEN,
    Debug: true,
    Ws: true,
})

**Comment by rictt** [comment]
same problem.

**Comment by zcpua** [comment]
Reproduction Code & All Logs
