### ISSUE TITLE
UpscaleApi failed with status 400

### ISSUE THREAD

**Issue by snwfdhmp** [erictik/midjourney-client#160]
### the code that reproduces this issue or a replay of the bug

```js
import { Midjourney } from "midjourney"
import fs from "fs"

const client = new Midjourney({
  ServerId: "***",
  ChannelId: "***",
  SalaiToken: "***",
  Debug: true,
  Ws: true,
})

async function run() {
  await client.init()

  const Imagine = await client.Imagine(process.argv[2], (uri, progress) => {
    // console.log("Imagine", uri, "progress", progress)
  })

  const Upscale = await client.Upscale(
    Imagine.content,
    2,
    Imagine.id,
    Imagine.hash,
    (uri, progress) => {
      // console.log("Upscale", uri, "progress", progress)
    }
  )
  console.log({ uri: Upscale.uri })
  let imageUrl = Upscale.uri
  if (process.argv[3]) {
    fs.writeFileSync(process.argv[3], imageUrl)
  }
  client.Close()
  setTimeout(() => process.exit(0), 1000)
}

run()
```

### Describe the bug

**Describe the bug**
UpscaleApi failed with status 400

**Expected behavior**
UpscaleApi returns 204

### error log

Error: UpscaleApi failed with status 400
    at Midjourney.Upscale (/Users/snwfdhmp/Dev/workspaces/gpt/llm/.local/node_modules/midjourney/libs/midjourney.js:163:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///Users/snwfdhmp/Dev/workspaces/gpt/llm/.local/content-generation/ebooks/useMidjourney.js:20:19)

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-client/blob/main/example/upscale-ws.ts

**Comment by zcpua** [comment]
> @zcpua ?

![20230626-230056](https://github.com/erictik/midjourney-client/assets/34678575/887443d4-2d53-4eab-b450-ffef34591133)

**Comment by lys623** [comment]
![image](https://github.com/erictik/midjourney-client/assets/4364314/d38df9d5-b857-4840-a5cd-8c767047f90e)
where is flags?

**Comment by zcpua** [comment]
last version

**Comment by snwfdhmp** [comment]
error message unclear, API breaking changes should be warned @zcpua (regardless of the reason of the change)
