### ISSUE TITLE
ImagineApi failed with status 400

### ISSUE THREAD

**Issue by smz8023** [erictik/midjourney-client#163]
### the code that reproduces this issue or a replay of the bug

import fetch from 'node-fetch'
import { Midjourney } from 'midjourney'
import { SocksProxyAgent } from 'socks-proxy-agent';
import Koa  from  'koa'; // 引入koa
import Router from 'koa-router'; // 引入koa-router
const agent = new SocksProxyAgent('socks://127.0.0.1:7890', { keepAlive: true });
async  function fetchProxy(input, init = {}) {
  console.log('input', input);
  console.log('init', init);
  // 添加代理
  init.agent = agent;
  init.size = 1000 * 1024 * 1024

  const data = await fetch(input, init)
  console.log('data=====', data);
  return data // fetch(input, init)
}

const mjClient = new Midjourney({
  ServerId: '1112750591391825970',
  ChannelId: '1112759787067805799',
  SalaiToken: ',
  Debug: true,
  fetch: fetchProxy,
  // Ws: true
})
const app = new Koa(); // 创建koa应用
const router = new Router(); // 创建路由，支持传递参数
router.get('/', async (ctx) => {

     const data = await mjClient.Imagine('cat')
})
app.use(router.routes());
app.listen(3000, () => {
    console.log('应用已经启动，http://localhost:3000');
})

### Describe the bug

请求这个接口的时候https://discord.com/api/v9/interactions

### error log

{
    type: 'default',
    url: 'https://discord.com/api/v9/interactions',
    status: 400,
    statusText: 'Bad Request',
    headers: {
      'alt-svc': 'h3=":443"; ma=86400',
      'cf-cache-status': 'DYNAMIC',
      'cf-ray': '7de2ce418b6c25f0-NRT',
      connection: 'keep-alive',
      'content-length': '189',
      'content-security-policy': "frame-ancestors 'none'; default-src 'none'",
      'content-type': 'application/json',
      date: 'Wed, 28 Jun 2023 03:22:30 GMT',
      nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
 
      server: 'cloudflare',
      'set-cookie': [Array],
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      via: '1.1 google',
      'x-content-type-options': 'nosniff'
    },
    counter: 0,
    highWaterMark: 16384
  }

**Comment by zcpua** [comment]
u can try it

**Comment by zcpua** [comment]
same issue #22
