### ISSUE TITLE
deployed to vercel.com fail

### ISSUE THREAD

**Issue by allentofight** [erictik/midjourney-client#77]
You say remove zlib, use isomorphic-ws to support edge function, serverless deployment, but When I deployed to vercel.com ,it still failed, the error is the following:

```
Error: The Edge Function "api" is referencing unsupported modules:
--
The Edge Function "api" is referencing unsupported modules: - vercel/path0/dist/index.mjs: https, http, net, tls, crypto, stream, url, zlib

```
maybe it's related to the websocket

**Comment by zcpua** [comment]
https://github.com/erictik/midjourney-ui
